test_delete_queue (__main__.TestExercice) ... FAIL
test_delete_stack (__main__.TestExercice) ... FAIL
test_reverse (__main__.TestExercice) ... ok
test_sort_queue (__main__.TestExercice) ... FAIL
test_sort_stack (__main__.TestExercice) ... FAIL
test_string_and_structs (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_string_and_structs (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 91, in test_string_and_structs
    fifo.put_many("Yeet")
TypeError: put_many() missing 1 required positional argument: 'items'

======================================================================
FAIL: test_delete_queue (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 53, in test_delete_queue
    'Mauvaise reponse'
AssertionError: [] != [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19] : Mauvaise reponse

======================================================================
FAIL: test_delete_stack (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 38, in test_delete_stack
    'Mauvaise reponse'
AssertionError: [] != [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18] : Mauvaise reponse

======================================================================
FAIL: test_sort_queue (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 83, in test_sort_queue
    'Mauvaise reponse'
AssertionError: [] != [6, 81, 101, 105, 246, 288, 452, 455, 647,[50 chars] 982] : Mauvaise reponse

======================================================================
FAIL: test_sort_stack (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 68, in test_sort_stack
    'Mauvaise reponse'
AssertionError: [] != [97, 111, 177, 183, 207, 278, 387, 453, 48[52 chars] 973] : Mauvaise reponse

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=4, errors=1)
