test_delete_queue (__main__.TestExercice) ... FAIL
test_delete_stack (__main__.TestExercice) ... ERROR
test_reverse (__main__.TestExercice) ... ok
test_sort_queue (__main__.TestExercice) ... FAIL
test_sort_stack (__main__.TestExercice) ... FAIL
test_string_and_structs (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_delete_stack (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 33, in test_delete_stack
    output = exercice.delete_nth_from_stack(lifo, len(lifo) - 1)
  File "/home/runner/work/c01_ch6_exercices_3-marianachng/c01_ch6_exercices_3-marianachng/exercice.py", line 30, in delete_nth_from_stack
    for i in range(data):
TypeError: 'Stack' object cannot be interpreted as an integer

======================================================================
ERROR: test_string_and_structs (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 91, in test_string_and_structs
    fifo.put_many("Yeet")
TypeError: put_many() missing 1 required positional argument: 'items'

======================================================================
FAIL: test_delete_queue (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 53, in test_delete_queue
    'Mauvaise reponse'
AssertionError: [] != [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19] : Mauvaise reponse

======================================================================
FAIL: test_sort_queue (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 83, in test_sort_queue
    'Mauvaise reponse'
AssertionError: [54, [31 chars]18, 421, 500, 542, 544, 667, 682, 788, 795, 851, 886, 912, 980] != [54, [31 chars]18, 421, 500, 542, 544, 667, 682, 788, 795, 851, 886, 912, 980] : Mauvaise reponse

======================================================================
FAIL: test_sort_stack (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 68, in test_sort_stack
    'Mauvaise reponse'
AssertionError: [22, [27 chars]87, 504, 534, 543, 551, 713, 754, 765, 779, 837, 865, 922, 935] != [22, [27 chars]87, 504, 534, 543, 551, 713, 754, 765, 779, 837, 865, 922, 935] : Mauvaise reponse

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=3, errors=2)
